apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: populate-cp4d
spec:
  params:
    - name: overrides
      type: string
  workspaces:
    - name: shared-workspace
  results:
    - name: output-file
      description: the final file created by this fetch and override
  steps:
    - name: clone-repo
      image: alpine/git
      workingDir: $(workspaces.shared-workspace.path)
      script: |
        git clone https://github.com/itz-public/k8s-manifests.git $(workspaces.shared-workspace.path)/repo
    - name: apply-overrides
      image: mikefarah/yq:4.45.4
      workingDir: $(workspaces.shared-workspace.path)
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        export BASE=$(workspaces.shared-workspace.path)/repo/cloud-pak-deployer/cp4d/cp4d.yaml
        echo "$(params.overrides)" > /tmp/overrides.yaml

        yq ea '
          select(fileIndex == 0) as $base |
          select(fileIndex == 1) as $over |
          $base.cp4d[0] *= ($over.cp4d[0] | with_entries(select(.key != "cartridges"))) |
          $base.cp4d[0].cartridges = (
            $base.cp4d[0].cartridges
            | map(
                . as $b |
                ($over.cp4d[0].cartridges // [] | map(select(.name == $b.name)) | .[0]) // {} * $b
              )
          ) |
          $base
        ' "$BASE" /tmp/overrides.yaml > $(workspaces.shared-workspace.path)/cp4d.yaml
        echo "Final merged YAML written to: $(workspaces.shared-workspace.path)/cp4d.yaml"
        echo "$(workspaces.shared-workspace.path)/cp4d.yaml" > $(results.output-file.path)
