apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: configure-deployer
  namespace: default
spec:
  pipelineRef:
    name: configure-deployer
  params:
    - name: deployer-namespace
      value: cloud-pak-deployer
    - name: deployer-sa
      value: cpd-sa
    - name: ibm-entitlement-key
      value: "" # Or pass one if needed at runtime
    - name: cloudpak
      value: cp4d
    - name: file-storage
      value: ocs-external-storagecluster-cephfs
    - name: block-storage
      value: ocs-external-storagecluster-ceph-rbd
    - name: deployer-pvc
      value: cloud-pak-deployer-pvc
    - name: override_url
      value: https://raw.githubusercontent.com/itz-public/k8s-manifests/refs/heads/main/cloud-pak-deployer/cp4d/minimal.yaml
  workspaces:
    - name: shared-configuration
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
