---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: configure-deployer
spec:
  params:
    - name: deployer-namespace
      type: string
      default: "cloud-pak-deployer"
    - name: deployer-sa
      type: string
      default: "cpd-sa"
    - name: ibm-entitlement-key
      type: string
      default: ""
    - name: cloudpak
      type: string
      default: ""
tasks:
  - name: create-namespace-for-cloud-pak-deployer
    displayName: Create Namespace For Cloud Pak Deployer
    taskRef:
      kind: Task
      name: create-namespace
    params:
      - name: namespace
        value: $(params.deployer-namespace)
  - name: create-sa-for-cp-deployer
    displayName: Create Service Account for Cloud Pak Deployer
    runAfter:
      - create-namespace-for-cloud-pak-deployer
    taskRef:
      kind: Task
      name: create-service-account
    params:
      - name: namespace
        value: $(params.deployer-namespace)
      - name: sa
        value: $(params.deployer-sa)
  - name: bind-scc-for-sa
    displayName: Bind the privileged SCC for the cloud pak deployer sa
    runAfter:
      - create-sa-for-cp-deployer
    taskRef:
      kind: Task
      name: create-scc-rolebinding
    params:
      - name: scc
        value: privileged
      - name: sa
        value: $(params.deployer-sa)
      - name: namespace
        value: $(params.deployer-namespace)
  - name: bind-cr-for-sa
    displayName: Bind the cluster admin privileges for cloud pak deployer sa
    runAfter:
      - bind-scc-for-sa
    taskRef:
      kind: Task
      name: create-cr-rolebinding
    params:
      - name: cr
        value: cluster-admin
      - name: sa
        value: $(params.deployer-sa)
      - name: namespace
        value: $(params.deployer-namespace)
  - name: get-tz-ibm-entitlement-key
    displayName: Get the TZ ibm entitlement key
    runAfter:
      - bind-cr-for-sa
    params:
      - name: KEY_ID
        value: 968d7819-f2c5-7b67-c420-3c6bfd51521e
      - name: SECRETS_MANAGER_ENDPOINT_URL
        value: >-
          https://afa20521-cd75-4864-843f-e59fd0ffd49d.us-south.secrets-manager.appdomain.cloud
    taskRef:
      kind: Task
      name: ibmcloud-secrets-manager-get
  - name: create-ibm-entitlement-secret
    displayName: Create the IBM Entitlement Secret for Cloud Pak Deployer
    runAfter:
      - get-tz-ibm-entitlement-key
    params:
      - name: ibm-entitlement-key
        value: $(params.ibm-entitlement-key)
      - name: tz-ibm-entitlement-key
        value: $(tasks.get-tz-ibm-entitlement-key.results.secret-value)
      - name: namespace
        value: $(params.namespace)
  - name: deploy-cp4d
    taskRef:
      kind: Pipeline
      name: deployer-cp4d-pipeline
    when:
      - input: $(params.cloudpak)
        operator: in
        values: ["cp4d"]
  - name: deploy-cp4i
    taskRef:
      kind: Pipeline
      name: deployer-cp4i-pipeline
    when:
      - input: $(params.cloudpak)
        operator: in
        values: ["cp4i"]
  - name: deploy-cp4ba
    taskRef:
      kind: Pipeline
      name: deployer-cp4ba-pipeline
    when:
      - input: $(params.cloudpak)
        operator: in
        values: ["cp4ba"]
