apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: configure-deployer
  namespace: default
spec:
  pipelineRef:
    name: configure-deployer
  params:
    - name: deployer-namespace
      value: cloud-pak-deployer
    - name: deployer-sa
      value: cpd-sa
    - name: ibm-entitlement-key
      value: "" # Or pass one if needed at runtime
    - name: cloudpak
      value: cp4d
    - name: file-storage
      value: ocs-external-storagecluster-cephfs
    - name: block-storage
      value: ocs-external-storagecluster-ceph-rbd
    - name: deployer-pvc
      value: cloud-pak-deployer-pvc
    - name: overrides
      value: |
        global_config:
          environment_name: demo
          cloud_platform: existing-ocp
          confirm_destroy:
        openshift:
          - name: cpd-demo
            openshift_storage:
              - storage_name: test
                storage_type: custom
                ocp_storage_class_file: ocs-external-storagecluster-cephfs
                ocp_storage_class_block: ocs-external-storagecluster-ceph-rbd
        cp4d:
          - project: cpd
            openshift_cluster_name: cpd-demo
            cp4d_version: 5.2.0
            cp4d_entitlement:
              - cpd-enterprise
            accept_licenses: True
            operators_project: cpd-operators
            state: installed
            cartridges:
              - name: scheduler
                state: installed
  workspaces:
    - name: shared-configuration
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
